# Cross-compilation configuration for Cargo
# This file should be placed in ~/.cargo/config.toml or .cargo/config.toml in your project

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-pc-windows-msvc]
# Windows ARM64 support - requires Visual Studio with ARM64 tools
# No additional linker configuration needed if VS is properly installed

[target.x86_64-pc-windows-msvc]
# Windows x64 support - default target on Windows
# No additional linker configuration needed
